int core_exception_context_size = 0;

void core_exception_context_init (void)
{
}

